# Generated by Django 6.0.3 on 2026-05-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_imr_probabilidade_media_amplitude_probabilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imr',
            name='alertas',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='media_amplitude',
            name='alertas',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='p',
            name='alertas',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='u',
            name='alertas',
            field=models.JSONField(default=dict),
        ),
    ]
