# Generated by Django 6.0.3 on 2026-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imr_alertas_media_amplitude_alertas_p_alertas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imr',
            name='regra',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='media_amplitude',
            name='regra',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='p',
            name='regra',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='u',
            name='regra',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
