# Generated by Django 6.0.3 on 2026-06-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_imr_regra_media_amplitude_regra_p_regra_u_regra'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraBarulho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_picos', models.IntegerField()),
                ('n', models.IntegerField(default=6000)),
                ('p', models.FloatField(default=0)),
                ('lc', models.FloatField(default=0)),
                ('lsc', models.FloatField(default=0)),
                ('lic', models.FloatField(default=0)),
                ('alertas', models.JSONField(default=dict)),
                ('fora_controle', models.BooleanField(default=False)),
            ],
        ),
    ]
