# Generated by Django 6.0.6 on 2026-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_leiturabarulho'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraRuido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('leq', models.FloatField(default=0)),
                ('lmax', models.FloatField(default=0)),
                ('mr', models.FloatField(default=0)),
                ('lc_i', models.FloatField(default=0)),
                ('lsc_i', models.FloatField(default=0)),
                ('lic_i', models.FloatField(default=0)),
                ('am_media', models.FloatField(default=0)),
                ('alertas', models.JSONField(default=dict)),
                ('fora_controle', models.BooleanField(default=False)),
            ],
        ),
    ]
